# Generated by Django 2.0.7 on 2019-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190506_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='notify',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
