# Generated by Django 2.0.7 on 2019-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190507_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='notify_when',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
