# Generated by Django 2.0.7 on 2019-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_email_notify_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='notify_when',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('ST', 'Saturday')], max_length=15),
        ),
    ]
