# Generated by Django 2.0.7 on 2019-05-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190507_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='notify_when',
            field=models.DateTimeField(verbose_name='When to notify'),
        ),
    ]
