# Generated by Django 2.0.7 on 2019-05-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190507_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('ST', 'Saturday')], default='Sunday', max_length=15),
        ),
    ]
