# Generated by Django 2.0.7 on 2019-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=15, verbose_name='Day of the week'),
        ),
    ]
